/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.54
 * Generated at: 2026-06-17 18:52:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class alunos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"pt-br\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles.css\">\n");
      out.write("    <title>DevGym - Gestão de Alunos</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"sidebar\">\n");
      out.write("        <h2>DevGym</h2>\n");
      out.write("        <nav>\n");
      out.write("            <a href=\"index.jsp\">Dashboard</a>\n");
      out.write("            <a href=\"alunos.jsp\" class=\"active\">Alunos</a>\n");
      out.write("            <a href=\"personais.jsp\">Personais</a>\n");
      out.write("        </nav>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"main-content\">\n");
      out.write("        <h1>Gestão de Alunos</h1>\n");
      out.write("        \n");
      out.write("        <form method=\"post\" action=\"cadastrarAluno.jsp\">\n");
      out.write("            <div class=\"card-form\">\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <input type=\"text\" name=\"nome\" placeholder=\"Nome do Aluno\" style=\"flex: 1;\" required>\n");
      out.write("                    <input type=\"text\" name=\"cpf\" placeholder=\"CPF\" maxlength=\"14\" style=\"flex: 1;\" required>\n");
      out.write("                    <input type=\"date\" name=\"data_nascimento\" style=\"flex: 1;\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <input type=\"text\" name=\"telefone\" placeholder=\"Telefone\" maxlength=\"12\" style=\"flex: 1;\" required>\n");
      out.write("                    <input type=\"text\" name=\"endereco\" placeholder=\"Endereço\" style=\"flex: 1;\" required>\n");
      out.write("                    <button type=\"submit\" class=\"btn-save\">Cadastrar</button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        <div class=\"search-bar\">\n");
      out.write("            <form action=\"alunos.jsp\" method=\"get\">\n");
      out.write("                <input type=\"text\" name=\"busca\" placeholder=\"Buscar por CPF...\">\n");
      out.write("                <button type=\"submit\" class=\"btn-search\">Buscar</button>\n");
      out.write("                \n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <table>\n");
      out.write("            <thead>\n");
      out.write("                <tr>\n");
      out.write("                    <th>ID</th>\n");
      out.write("                    <th>Nome</th>\n");
      out.write("                    <th>CPF</th>\n");
      out.write("                    <th>Data Nasc.</th>\n");
      out.write("                    <th>Telefone</th>\n");
      out.write("                    <th>Endereço</th>\n");
      out.write("                    <th>Ações</th>\n");
      out.write("                </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>\n");
      out.write("                ");

                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetodevgym", "root", "13062013");
                    
                    String busca = request.getParameter("busca");
                    String sql = "SELECT * FROM alunos";
                    
                    if(busca != null && !busca.isEmpty()){
                        sql = "SELECT * FROM alunos WHERE cpf LIKE CONCAT('%', ?, '%')";
                    }
                    
                    PreparedStatement st = con.prepareStatement(sql);
                    if(busca != null && !busca.isEmpty()){
                        st.setString(1, busca);
                    }
                    
                    ResultSet rs = st.executeQuery();
                    
                    while(rs.next()) {
                
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td>");
      out.print( rs.getString("id_aluno") );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getString("nome") );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getString("cpf") );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getDate("data_nascimento") );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getString("telefone") );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getString("endereco") );
      out.write("</td>\n");
      out.write("                        <td>\n");
      out.write("                            <a href=\"editarAluno.jsp?cpf=");
      out.print( rs.getString("cpf") );
      out.write("\" class=\"btn-edit\">Editar</a>\n");
      out.write("                            <a href=\"excluirAluno.jsp?id=");
      out.print( rs.getString("id_aluno") );
      out.write("\" \n");
      out.write("                               onclick=\"return confirm('Tem certeza que deseja excluir este aluno?')\" \n");
      out.write("                               class=\"btn-delete\">Excluir</a>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                ");
 
                    } 
                    rs.close();
                    st.close();
                    con.close(); 
                
      out.write("\n");
      out.write("            </tbody>\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
